### ISSUE TITLE
Home page appeard as "test"

### ISSUE THREAD

**Issue by thorildor** [momo-i/XtraUpload#18]
Hello,

I downloaded xtraupload before the commit of 3.1.0 to be sure to have no bug(https://github.com/momo-i/XtraUpload/tree/ad558f72b4cdb6000faec734b9162add320e5350) and as you said to me but after 2/3 minutes the homepage and on all page it's appeard "test" and I can't do anything.

Thanks

**Comment by momo-i** [comment]
Yes, It is not workable yet. Currently, I am working hard In order to run the plupload. It is very difficult for me, but I want to be able to work until next week.

**Comment by thorildor** [comment]
Great, thanks for you work!

**Comment by momo-i** [comment]
Because I have developed this as a hobby.

It was originally (around 2012) what I was interested. But, because there were many errors in the latest PHP, I was simply to work. I'm not even in genuine developers rather than the original developer. So I have to leisurely commit, and have to leisurely development. ;)

**Comment by momo-i** [comment]
I completed to migrate to plupload. please test alpha version.
